### ISSUE TITLE
Missing .deb release 1.5.1

### ISSUE THREAD

**Issue by Mortega5** [naevatec/kms-siprtpendpoint#8]
I've noticed that code has been committed as release 1.5.1, but the .deb files haven't been published.

Could the .deb files be made available in the 'releases' section on GitHub? We are using these files to generate Docker images.

Thanks in advance.

**Comment by slabajo** [comment]
Hi Miguel,


We will try to provide a .deb package soon, but we need some little time as
we are busy with some other projects.










*Saúl Pablo Labajo Izquierdo*
CEO



www.naevatec.com
email:    ***@***.***

mobile:   +34 606 697134

phone:    +34 911 407507



*In accordance with the provisions of the REGULATION (EU) 2016/679 of
protection of personal data, we inform you that the data you provide us
will be incorporated into the treatment system owned by TIKAL TECHNOLOGIES
SL with CIF B85986669 and address located at Calle Chile, Nº 10, 28290 -
Las Rozas de Madrid (Madrid), for the purpose of Advertising and Commercial
Prospecting; other purposes. Your data may be processed by third parties
(they will be responsible for the treatment of your data for a lawful
contractual purpose, for example, our computer maintenance company)
demanding the same level of rights, obligations and established
responsibilities. Your data will be kept for the period strictly necessary.
They will be erased when a time has elapsed without making use of them. You
agree to notify us of any variation in the data. You can exercise the
rights of access, rectification, limitation of treatment, deletion,
portability and opposition to the processing of your personal data by
addressing your request to the postal address indicated above or to the
email ***@***.*** ***@***.***>. You can go to the competent
Control Authority to present the claim that you consider appropriate.*

**Comment by slabajo** [comment]
Sorry for the delay in providing this. It is now released and also latest 1.6.0
